apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.mycircle.downloader'
version = '1.0.0'

android {
    namespace 'com.mycircle.downloader'
    compileSdkVersion 34
    defaultConfig {
        minSdkVersion rootProject.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 24
        targetSdkVersion 34
    }

    lintOptions {
        abortOnError false
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}


repositories {
    mavenCentral()
    google()
}

dependencies {
    implementation project(':expo-modules-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.23"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
}
